# Generated by Django 6.0.3 on 2026-04-03 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('category', models.CharField(blank=True, max_length=100)),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Mirai Experiential School', max_length=100)),
                ('tagline', models.CharField(default='Where Learning Comes Alive', max_length=200)),
                ('primary_color', models.CharField(default='#AA4A44', help_text='Hex e.g. #AA4A44', max_length=7)),
                ('secondary_color', models.CharField(default='#77966D', max_length=7)),
                ('accent_color', models.CharField(default='#AFBFAA', max_length=7)),
                ('phone', models.CharField(default='+91 98765 43210', max_length=30)),
                ('email', models.EmailField(default='admissions@miraieschool.com', max_length=254)),
                ('address', models.TextField(default='NH-48, Gurugram, Haryana 122001')),
                ('established_year', models.PositiveSmallIntegerField(default=2018)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('hero_tagline', models.CharField(default='Where Learning Comes Alive', max_length=300)),
                ('meta_description', models.TextField(blank=True, default='Mirai Experiential School — IB curriculum, experiential learning, and residential boarding.', max_length=300)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='color',
            field=models.CharField(default='#AA4A44', help_text='Category badge color', max_length=7),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/'),
        ),
        migrations.AddField(
            model_name='facility',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='facilities/'),
        ),
        migrations.AddField(
            model_name='program',
            name='color_accent',
            field=models.CharField(default='#AA4A44', help_text='Card accent color hex', max_length=7),
        ),
        migrations.AddField(
            model_name='stat',
            name='icon',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='testimonials/'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='grade_applying',
            field=models.CharField(choices=[('EYP', 'Early Years'), ('PYP', 'Primary (Gr 1–5)'), ('6', 'Grade 6'), ('7', 'Grade 7'), ('8', 'Grade 8'), ('9', 'Grade 9'), ('10', 'Grade 10'), ('11', 'Grade 11'), ('12', 'Grade 12')], max_length=10),
        ),
        migrations.AlterField(
            model_name='program',
            name='highlights',
            field=models.TextField(help_text='One highlight per line'),
        ),
    ]
