# Generated by Django 6.0.3 on 2026-04-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_galleryimage_sitesettings_blogcategory_color_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enquiry',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'Enquiry', 'verbose_name_plural': 'Enquiries'},
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='email',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='grade_applying',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='message',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='parent_name',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='student_name',
        ),
        migrations.AddField(
            model_name='enquiry',
            name='aadhaar_passport_no',
            field=models.CharField(blank=True, max_length=50, verbose_name='Aadhaar / Passport No.'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='academic_session',
            field=models.CharField(blank=True, max_length=20, verbose_name='Academic Session'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='address_city',
            field=models.CharField(default='', max_length=100, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='address_pin',
            field=models.CharField(default='', max_length=10, verbose_name='PIN Code'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='address_state',
            field=models.CharField(default='', max_length=100, verbose_name='State'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='address_street',
            field=models.TextField(default='', verbose_name='House No. / Street'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='applying_for_grade',
            field=models.CharField(blank=True, max_length=10, verbose_name='Grade (within programme)'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='applying_for_program',
            field=models.CharField(choices=[('EYP', 'Early Years Programme (EYP)'), ('PYP', 'Primary Years Programme (PYP)'), ('MYP', 'Middle Years Programme (MYP)'), ('DP', 'Diploma Programme (DP)')], default='EYP', max_length=10, verbose_name='Applying for Programme'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='awards_recognitions',
            field=models.TextField(blank=True, verbose_name='Awards / Recognitions'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='boarding_special_considerations',
            field=models.TextField(blank=True, verbose_name='Boarding Special Considerations'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='boarding_type',
            field=models.CharField(choices=[('day', 'Day Scholar'), ('weekly', 'Weekly Boarding'), ('full', 'Full Boarding')], default='day', max_length=10, verbose_name='Boarding Requirement'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='counsellor_assigned',
            field=models.CharField(blank=True, max_length=100, verbose_name='Counsellor Assigned'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='current_curriculum',
            field=models.CharField(blank=True, choices=[('IB', 'IB'), ('CBSE', 'CBSE'), ('ICSE', 'ICSE'), ('IGCSE', 'IGCSE'), ('state_board', 'State Board'), ('other', 'Other')], max_length=20, verbose_name='Current Curriculum'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='current_curriculum_other',
            field=models.CharField(blank=True, max_length=100, verbose_name='Current Curriculum (Other)'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='current_school_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Current School Name'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='declaration_accepted',
            field=models.BooleanField(default=False, verbose_name='Declaration Accepted'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='declaration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Declaration Date'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='father_email',
            field=models.EmailField(default='', max_length=254, verbose_name="Father's Email ID"),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='father_income_bracket',
            field=models.CharField(blank=True, choices=[('below_5L', 'Below 5L'), ('5_10L', '5–10L'), ('10_20L', '10–20L'), ('above_20L', '20L+')], max_length=20, verbose_name="Father's Annual Income Bracket"),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='father_mobile',
            field=models.CharField(default='', max_length=20, verbose_name="Father's Mobile No."),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='father_name',
            field=models.CharField(default='', max_length=150, verbose_name="Father's Full Name"),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='father_occupation',
            field=models.CharField(blank=True, max_length=150, verbose_name="Father's Occupation / Designation"),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='father_organization',
            field=models.CharField(blank=True, max_length=200, verbose_name="Father's Organization / Business"),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='father_qualification',
            field=models.CharField(blank=True, max_length=150, verbose_name="Father's Qualification"),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True, verbose_name='Follow-up Date'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='male', max_length=10, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='heard_via',
            field=models.CharField(blank=True, max_length=300, verbose_name='How Did You Hear About Us?'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='heard_via_other',
            field=models.CharField(blank=True, max_length=100, verbose_name='How Did You Hear (Other)'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='ib_awareness',
            field=models.TextField(blank=True, verbose_name='How Much Do You Know About IB?'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='inquiry_no',
            field=models.CharField(blank=True, max_length=30, verbose_name='Inquiry No.'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='interaction_date',
            field=models.DateField(blank=True, null=True, verbose_name='Interaction Date'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='learning_support_details',
            field=models.TextField(blank=True, verbose_name='Learning Support Details'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='learning_support_required',
            field=models.BooleanField(default=False, verbose_name='Learning Support Required'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='medical_conditions_allergies',
            field=models.TextField(blank=True, verbose_name='Medical Conditions / Allergies'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='mother_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name="Mother's Email ID"),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='mother_mobile',
            field=models.CharField(blank=True, max_length=20, verbose_name="Mother's Mobile No."),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='mother_name',
            field=models.CharField(blank=True, max_length=150, verbose_name="Mother's Full Name"),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='mother_occupation',
            field=models.CharField(blank=True, max_length=150, verbose_name="Mother's Occupation / Designation"),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='mother_organization',
            field=models.CharField(blank=True, max_length=200, verbose_name="Mother's Organization / Business"),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='mother_qualification',
            field=models.CharField(blank=True, max_length=150, verbose_name="Mother's Qualification"),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='school_expectations',
            field=models.TextField(blank=True, verbose_name='Expectations from School'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='sibling1_grade',
            field=models.CharField(blank=True, max_length=20, verbose_name='Sibling 1 Grade'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='sibling1_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Sibling 1 Name'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='sibling1_school',
            field=models.CharField(blank=True, max_length=200, verbose_name='Sibling 1 School'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='sibling2_grade',
            field=models.CharField(blank=True, max_length=20, verbose_name='Sibling 2 Grade'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='sibling2_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Sibling 2 Name'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='sibling2_school',
            field=models.CharField(blank=True, max_length=200, verbose_name='Sibling 2 School'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='student_full_name',
            field=models.CharField(default='', max_length=200, verbose_name="Student's Full Name"),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='student_preferred_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Preferred Name'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='student_strengths_interests',
            field=models.TextField(blank=True, verbose_name='Strengths / Interests'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='transport_pickup_location',
            field=models.CharField(blank=True, max_length=200, verbose_name='Pickup Location'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='transport_required',
            field=models.BooleanField(default=False, verbose_name='Transport Required'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='why_mirai_other',
            field=models.CharField(blank=True, max_length=200, verbose_name='Why Mirai — Other'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='why_mirai_reasons',
            field=models.CharField(blank=True, max_length=500, verbose_name='Why Mirai — Reasons'),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='color',
            field=models.CharField(default='#AA4A44', max_length=7),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='nationality',
            field=models.CharField(default='', max_length=100, verbose_name='Nationality'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('interaction_done', 'Interaction Done'), ('assessment_scheduled', 'Assessment Scheduled'), ('offered', 'Offered'), ('closed', 'Closed')], default='pending', max_length=30, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='program',
            name='color_accent',
            field=models.CharField(default='#AA4A44', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='primary_color',
            field=models.CharField(default='#AA4A44', max_length=7),
        ),
    ]
