# Generated by Django 4.2.30 on 2026-04-11 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_add_faq_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='email',
            field=models.EmailField(default='siddhant@nimt.ac.in', max_length=254),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone',
            field=models.CharField(default='+91 95999 31471', max_length=30),
        ),
    ]
